version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: reserva_db
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reserva_fisi
      MYSQL_USER: fisi
      MYSQL_PASSWORD: fisi
    ports: ["3306:3306"]
    volumes: ["mysql_data:/var/lib/mysql"]
  mailhog:
    image: mailhog/mailhog
    container_name: reserva_mailhog
    ports: ["1025:1025", "8025:8025"]
volumes:
  mysql_data:
